# CommonFiles.ps1
# These files are included in every build
# DO NOT include inferno/* files - they are only for development/IntelliSense

$commonFiles = @(
    "Common/Action/Action.cs",
    "Common/Action/FriendlyTargetedAction.cs",
    "Common/Conditions/Condition.cs",
    "Common/Conditions/InCombatCondition.cs",
    "Common/Conditions/IsSpellOffCooldownCondition.cs",
    "Common/group/Group.cs",
    "Common/group/PartyGroup.cs",
    "Common/group/RaidGroup.cs",
    "Common/group/Solo.cs",
    "Common/Selectors/UnitFilterChain/GetLowestUnit.cs",
    "Common/Selectors/UnitFilterChain/IsInRange.cs",
    "Common/Selectors/UnitFilterChain/IsNotDead.cs",
    "Common/Selectors/UnitFilterChain/IUnitFilterChain.cs",
    "Common/Selectors/FilterChainSelector.cs",
    "Common/Selectors/ISelector.cs",
    "Common/unit/PartyUnit.cs",
    "Common/unit/RaidUnit.cs",
    "Common/unit/PlayerUnit.cs",
    "Common/unit/Unit.cs",
    "Common/utilities/ActionQueuer.cs",
    "Common/utilities/JsonParser.cs",
    "Common/utilities/Logger.cs",
    "Common/utilities/TargetingMacros.cs",
    "Common/utilities/Throttler.cs",
    "Common/utilities/UnitUtilities.cs",
    "Common/ActionBook.cs",
    "Common/Boss.cs",
    "Common/Environment.cs",
    "Common/Gambit.cs",
    "Common/GambitSet.cs",
    "Common/GambitSetPicker.cs",
    "Common/PeneloRotation.cs",
    "Common/Target.cs",
    "Common/SpellMacroRegistry.cs"
)
